# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    com.docker.official-images.bashbrew.arch/docker: amd64
    io.kubernetes.cri-o.ContainerType/docker: container
    io.kubernetes.cri-o.ContainerType/formicaio: container
    io.kubernetes.cri-o.SandboxID/docker: bbda0434ab6e5d68cad4468acb64b79c9ca5812cf1ca05ccfadfeae76fbfbd1
    io.kubernetes.cri-o.SandboxID/formicaio: bbda0434ab6e5d68cad4468acb64b79c9ca5812cf1ca05ccfadfeae76fbfbd1
    io.kubernetes.cri-o.TTY/docker: "true"
    io.kubernetes.cri-o.TTY/formicaio: "true"
    io.podman.annotations.autoremove/docker: "FALSE"
    io.podman.annotations.autoremove/formicaio: "FALSE"
    io.podman.annotations.init/docker: "FALSE"
    io.podman.annotations.init/formicaio: "FALSE"
    io.podman.annotations.privileged/docker: "TRUE"
    io.podman.annotations.privileged/formicaio: "FALSE"
    io.podman.annotations.publish-all/docker: "FALSE"
    io.podman.annotations.publish-all/formicaio: "FALSE"
    org.opencontainers.image.base.digest/docker: sha256:a7685cf887742038828db60214dda4ecadfeda5744bd03429a64a876
    org.opencontainers.image.base.name/docker: docker:27-cli
    org.opencontainers.image.created/docker: "2024-08-27T23:04:15Z"
    org.opencontainers.image.revision/docker: 3a19522aa3c9bb06216f71f0d7323764e72c80be
    org.opencontainers.image.source/docker: https://github.com/docker-library/docker.git#3a19522aa3c9bb0621
    org.opencontainers.image.url/docker: https://hub.docker.com/_/docker
    org.opencontainers.image.version/docker: 27.2.0-dind
  creationTimestamp: "2024-12-12T07:19:57Z"
  labels:
    app: formicaio-pod
  name: formicaio-pod
spec:
  automountServiceAccountToken: false
  containers:
  - image: docker.io/library/docker@sha256:f9f72ad901a78f27be922b2d320bbc263174f12919c1b37e6a01f828fa904565
    name: docker
    ports:
    - containerPort: 8080
      hostPort: 52100
    resources: {}
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: /var/lib
      name: pod_volume_formicaio-pvc
    - mountPath: /var/run
      name: pod_volume_formicaio-pvc
    - mountPath: /var/lib/docker
      name: d55aa4edce241c00d1a5af5cd894aed7ee14b5c91ee231198c290d36f099f6b8-pvc
  - env:
    - name: DB_PATH
      value: /data
    - name: DOCKER_SOCKET_PATH
      value: /var/run/docker.sock
    image: docker.io/bochaco/formicaio:latest
    name: formicaio
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    tty: true
    volumeMounts:
    - mountPath: /var/run
      name: pod_volume_formicaio-pvc
    - mountPath: /data
      name: pod_volume_formicaio-pvc
  enableServiceLinks: false
  hostname: formicaio-pod
  restartPolicy: Never
  volumes:
  - name: pod_volume_formicaio-pvc
    persistentVolumeClaim:
      claimName: pod_volume_formicaio
  - name: d55aa4edce241c00d1a5af5cd894aed7ee14b5c91ee231198c290d36f099f6b8-pvc
    persistentVolumeClaim:
      claimName: d55aa4edce241c00d1a5af5cd894aed7ee14b5c91ee231198c290d36f099f6b8
status: {}

