# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-12-12T20:22:42Z"
  labels:
    app: formicaio-pod
  name: formicaio-pod
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - --data-root
    - /data/docker
    - --exec-root
    - /data/docker/exec
    - --host
    - unix:///var/run/docker.sock
    - --pidfile
    - /data/docker/docker.pid
    image: docker.io/library/docker@sha256:b0c1179ea32ad77bdb7b852b037e54b11022304c2f2662af1954ef53869314b2
    name: docker
    ports:
    - containerPort: 8080
      hostPort: 52100
    resources: {}
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: /data
      name: pod_volume_formicaio-pvc
    - mountPath: /var/lib/docker
      name: pod_volume_formicaio-pvc
    - mountPath: /var/run
      name: pod_volume_formicaio-pvc
  - env:
    - name: DOCKER_SOCKET_PATH
      value: /var/run/docker.sock
    - name: NODE_CONTAINER_IMAGE_TAG
      value: latest
    - name: DB_PATH
      value: /data
    image: docker.io/bochaco/formicaio:latest
    name: formicaio
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    tty: true
    volumeMounts:
    - mountPath: /data
      name: pod_volume_formicaio-pvc
    - mountPath: /var/run
      name: pod_volume_formicaio-pvc
  enableServiceLinks: false
  hostname: formicaio-pod
  restartPolicy: Never
  volumes:
  - name: pod_volume_formicaio-pvc
    persistentVolumeClaim:
      claimName: pod_volume_formicaio
status: {}

