# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-12-12T07:19:57Z"
  labels:
    app: formicaio-pod
  name: formicaio-pod
spec:
  automountServiceAccountToken: false
  containers:
  - image: docker.io/library/docker@sha256:f9f72ad901a78f27be922b2d320bbc263174f12919c1b37e6a01f828fa904565
    name: docker
    ports:
    - containerPort: 8080
      hostPort: 52100
    resources: {}
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: /var/lib
      name: pod_volume_formicaio-pvc
    - mountPath: /var/run
      name: pod_volume_formicaio-pvc
    - mountPath: /var/lib/docker
      name: d55aa4edce241c00d1a5af5cd894aed7ee14b5c91ee231198c290d36f099f6b8-pvc
  - env:
    - name: DB_PATH
      value: /data
    - name: DOCKER_SOCKET_PATH
      value: /var/run/docker.sock
    image: docker.io/bochaco/formicaio:latest
    name: formicaio
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    tty: true
    volumeMounts:
    - mountPath: /var/run
      name: pod_volume_formicaio-pvc
    - mountPath: /data
      name: pod_volume_formicaio-pvc
  enableServiceLinks: false
  hostname: formicaio-pod
  restartPolicy: Never
  volumes:
  - name: pod_volume_formicaio-pvc
    persistentVolumeClaim:
      claimName: pod_volume_formicaio
  - name: d55aa4edce241c00d1a5af5cd894aed7ee14b5c91ee231198c290d36f099f6b8-pvc
    persistentVolumeClaim:
      claimName: d55aa4edce241c00d1a5af5cd894aed7ee14b5c91ee231198c290d36f099f6b8
status: {}

