services:
  docker:
    image: docker:27.4.1-dind@sha256:3c8fb358b82767a38189e54a89a2ba8d71109f0a17efa87fd009ef8283c46df6
    privileged: true
    network_mode: host
    stop_grace_period: 1m
    environment:
      DOCKER_ENSURE_BRIDGE: "dind0:10.32.0.1/16"
    entrypoint: /entrypoint.sh
    command: >
      dockerd
        --bridge dind0
        --data-root /data/data
        --exec-root /data/exec
        --host unix:///data/docker.sock
        --pidfile /data/docker.pid
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./docker_volumes/docker:/data

  formicaio:
    image: bochaco/formicaio:latest
    privileged: true
    depends_on:
      - docker
    network_mode: host
    stop_grace_period: 5s
    environment:
      NODE_CONTAINER_IMAGE_TAG: latest
      DOCKER_SOCKET_PATH: /var/run/docker.sock
      DB_PATH: /data
    volumes:
      - ./docker_volumes/formicaio:/data
      - ./docker_volumes/docker:/var/run
    devices:
      - /dev:/dev