services:
  app_proxy:
    environment:
      APP_HOST: formicaio-apps-formicaio_formicaio_proxy_1
      APP_PORT: 52101
    container_name: formicaio-apps-formicaio_app_proxy_1
  formicaio_proxy:
    image: bochaco/formicaio_proxy:latest
    user: 1000:1000
    environment:
      FORMICAIO_ADDR: host.docker.internal:3100
      FORMICAIO_PROXY_PORT: 52101
      FORMICAIO_WIDGET_PROXY_PORT: 52111
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: formicaio-apps-formicaio_formicaio_proxy_1
  formicaio:
    image: bochaco/formicaio:latest-native
    privileged: true
    restart: on-failure
    user: 1000:1000
    network_mode: host
    stop_grace_period: 5s
    environment:
      DB_PATH: /data
      NODE_MGR_ROOT_DIR: /data
      LEPTOS_SITE_ADDR: 0.0.0.0:3100
    volumes:
      - ${APP_DATA_DIR}/data/formicaio:/data
    devices:
      - /dev:/dev
    container_name: formicaio-apps-formicaio_formicaio_1